### ISSUE TITLE
Support for different time format

### ISSUE THREAD

**Issue by searchformyusername** [idleice/whatsapp-analyzer#3]
I found that time I am getting in ios and android is coming to be `[07/08/20, 11:28:06 PM] ‎You created group “Cheating”` in this format. So if it supports is added then that would be very helpful. I can make a pr for this if u say.

**Comment by empicano** [comment]
The line formatting of the exported WhatsApp chat file depends (as far as I found out) on the OS and the language setting. As an example, the status message line you posted would be in German on a phone where the language is set to German. Who knows why they thought that this is a good idea 🤷‍♀️ I originally thought about adding support for the different formats, but there's no real way to collect every format there is, so i quickly abandoned that.

I think our best bet would be to devise a system that let's us add support for different formats over time, so that it would be straightforward to integrate when someone else encounters a format like e.g. `[08.07.2020, 11:28:06 PM] ‎Du hast die Gruppe "Cheating" erstellt`.

If you're in the mood for devising something like that, I'd be thrilled to review your PR. Otherwise I'd leave it at the current system, where one has to format to this kind of "standard" format that's noted in the README oneself, even if that's not the most elegant way.

**Comment by searchformyusername** [comment]
@empicano ok cool, I will try to make some imporvement in this
